# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  th-list:
    text: 分类
    url: /categories
  tags:
    text: 标签
    url: /tags
  code:
    text: 算法模板
    url: /templates.html
  address-card:
    text: 关于
    url: /about
  github:
    url: https://github.com/OhYee
    target: _blank
  comment:
    text: 评论系统
    url: /gitment
  qq:
    text: QQ联系
    url: http://wpa.qq.com/msgrd?v=3&uin=896817156&site=qq&menu=yes
    target: _blank
  link:
    text: 友情链接
    url: /about/index.html#友情链接

# 你的头像url
avatar: /logo.svg
# avatar link
avatar_link: /
# 头像背景图
brand: /brand.jpg
# favicon
favicon: /favicon.ico

# email
email: oyohyee@oyohyee.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#428bca'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: true
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: false

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 谢谢大爷~
  wechat: /wechatimg.jpg     #微信，关闭设为 false
  alipay: /alipayimg.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: false

# 是否开启toc
# toc: false
toc:
  list_number: false  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 文章标题：  <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.title %></a><br>文章地址：  <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a><br>创建时间：  <%- date(page.date) %><br>更新时间：  <%- date(page.updated) %>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否开启网易云跟帖， 填写app sdk中的app key
wangyi_ygt: false
# 是否使用 gitment，https://github.com/imsun/gitment
#gitment: false
gitment:
  owner: OhYee
  repo: OhYee.github.io
  client_id: 300bdf519730fd67e69c
  client_secret: 9a496df1c4da10cec1ec233379b9b3ef6a448c2e

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2016

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

# 动态定义title
# title_change: 
#   normal: 欢迎回来~
#   leave: 为什么在看别的页面啊？？？

# 设置为 true 发布后将使用 unpkg cdn
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: 豫ICP备17000379号
